esphome:
  name: "##Select name for device##"

esp8266:
#  board: esp01_1m
  board: d1

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hotspot"
    password: "0123456789"

captive_portal:


logger:
  # Serial logging is disabled by setting the logger baud rate to 0.
  # Otherwise the logger will occupy the hardware UART, making it unavailable
  # for receiving smart meter data on pin D7 (GPIO13).
  baud_rate: 0
  level: DEBUG
  
uart:
  rx_pin: D7
  rx_buffer_size: 2000
  baud_rate: 9600
  data_bits: 7
  parity: NONE
  stop_bits: 1

dsmr:
  request_pin: D5
  request_interval: 10s
  crc_check: false
  
sensor:
  - platform: dsmr
    energy_delivered_lux:
      name: Energy Delivered Total
      state_class: total_increasing
    energy_returned_tariff1:
      name: Energy Returned Tariff 1
    power_delivered:
      name: Power Delivered Total
    power_returned:
      name: Power Returned
    electricity_failures:
      name: Electricity Failures
    electricity_long_failures:
      name: Electricity Long Failures
    voltage_l1:
      name: Voltage L1
    voltage_l2:
      name: Voltage L2
    voltage_l3:
      name: Voltage L3
    current_l1:
      name: Current L1
    current_l2:
      name: Current L2
    current_l3:
      name: Current L3
    power_delivered_l1:
      name: Power Delivered L1
    power_delivered_l2:
      name: Power Delivered L2
    power_delivered_l3:
      name: Power Delivered L3
  - platform: uptime
    name: "AntP1 Uptime"      
    